### ISSUE TITLE
No delay?

### ISSUE THREAD

**Issue by justinputney** [bramley/phplist-plugin-autoresponder#8]
Is possible to send a message with no delay (immediately)?

Perhaps so that it doesn't even have to wait for a cron job?

**Comment by bramley** [comment]
That is not possible because the autoresponder processing needs to be initiated either manually or by a cron job. Then the actual sending needs to be initiated in the same way.

You might be able to modify the "welcome" email to include what you want to send, or have some text like "we will send xxxx within the next hour" and have the autoresponder do its normal processing.

**Comment by justinputney** [comment]
I thought this might be the case, but it was worth checking.

Can I put HTML into the Welcome email?

Thanks!
